### PR TITLE
Added method for finding all keys matching prefix

### PR DESCRIPTION
**Pull request by chrisspen**
Resolves issue #5.

### CODE REVIEW

**Comment by chrisspen** [comment]
Not sure what's wrong with the build, but it seems unrelated to the changes. Looks like Github no longer supports Python 3.6?

**Comment by jfjlaros** [comment]
I think so. I have removed support for Python 3.6 in some of my other projects too.

I still have not found any time to look at the code, but there is a holiday coming up...

**Comment by jfjlaros** [comment]
I made a couple of changes. Can you check and see whether you agree with them?

**Comment by chrisspen** [comment]
Looks good. Although are you sure you want to remove `run_tests`? That not only runs your tests but also initializes the environment.

How do you currently initialize your local environment for running tests?

**Comment by jfjlaros** [comment]
The main reason is that it is not platform independent.

It would be a good idea to document how to set up a development environment. Please see the last commit for this.

**Comment by jfjlaros** [comment]
So, are you happy with the changes?

**Comment by chrisspen** [comment]
Yep, looks fine. I'd prefer a platform dependent test script to no script at all, but it's your project, and that's a bit outside the scope of this PR anyways.

**Comment by jfjlaros** [comment]
Okay, thank you for your contribution. I will proceed with the merging then.

I have added your name to the credits if you do not mind.

**Comment by chrisspen** [comment]
Thanks.

**Pull request merged**
